---
- import_playbook: ssl.yml
- import_playbook: etcd.yml
- import_playbook: postgres.yml
- import_playbook: patroni.yml
- import_playbook: pgbackrest_repo.yml
- import_playbook: pgbackrest_client.yml
- import_playbook: monitoring.yml
- import_playbook: grafana.yml
