---
# Patroni cluster identity
patroni_group_name: postgres_cluster
patroni_scope: postgres-cluster
patroni_namespace: /service/

# DCS: etcd
patroni_dcs: etcd
patroni_etcd_hosts: "192.168.163.129:2379"

# PostgreSQL version
patroni_postgresql_version: 16
patroni_postgresql_port: 5432

# Users
patroni_superuser_username: postgres
patroni_superuser_password: "REDACTED"
patroni_replication_username: replicator
patroni_replication_password: "REDACTED"

# Installation
patroni_install: true
patroni_install_from_pip: true

# pg_hba managed by Patroni
patroni_postgresql_pg_hba:
  - { type: "local", database: "all", user: "postgres", method: "peer" }
  - { type: "host", database: "all", user: "all", address: "127.0.0.1/32", method: "scram-sha-256" }
  - { type: "host", database: "all", user: "all", address: "::1/128", method: "scram-sha-256" }
  - { type: "host", database: "replication", user: "replicator", address: "0.0.0.0/0", method: "scram-sha-256" }

# PostgreSQL parameters
patroni_postgresql_parameters:
  - { option: "unix_socket_directories", value: "/var/run/postgresql" }
  - { option: "wal_log_hints", value: "on" }

# Watchdog off for lab
patroni_watchdog_mode: 'off'

# REST API
patroni_restapi_port: 8008

# Integration with claranet.postgresql
patroni_prepare_for_postgresql_role: true
patroni_set_pg_conn_vars: true
patroni_set_pg_replication_role: true

# Data and config directories
patroni_postgresql_data_dir: /var/lib/postgresql/16/main
patroni_postgresql_config_dir: /etc/postgresql/16/main
